name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: sicpa-foundations/actions/external/action-semantic-pull-request@feature/semantic-release-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
